added getNumCardsReviewedByDay action
FooSoft/anki-connect pull request #239
Opened 2021-02-28 23:47 UTC by qharscoet

Might add options to filter by decks or something but for now seems to be usable

2021-03-05 04:04 UTC, FooSoft requested changes

2021-03-05 04:04 UTC, FooSoft commented on actions/statistics.md
> +            ['2021-02-28', 124],
These are single quotes, so it's not valid JSON

2021-03-05 04:04 UTC, FooSoft commented on plugin/__init__.py
> +        return self.database().all("select date(id/1000 - ?, 'unixepoch', 'localtime') as day, count() from revlog group by day order by day desc",
Single quotes in python strings please

2021-03-05 04:04 UTC, FooSoft commented
Please also add some basic tests to make sure that we are at least calling these APIs.

2021-03-06 14:56 UTC, qharscoet commented
Indeed, sorry for the wrong quotes.
Also added basic test inspired by the ones for the other stats actions.

2021-03-06 17:58 UTC, FooSoft commented
Looks good, thanks!

2021-03-06 17:58 UTC, merged